-- ==========================================
-- SCHEMA.SQL
-- Student Management System
-- Author: Fatoumata Bamba KEITA
-- ==========================================

-- TABLE STUDENTS
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    date_of_birth DATE
);

-- TABLE COURSES
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    credit NUMBER(2) NOT NULL
);

-- TABLE ENROLLMENTS
CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    semester VARCHAR2(20),
    CONSTRAINT fk_student FOREIGN KEY (student_id)
        REFERENCES students(student_id),
    CONSTRAINT fk_course FOREIGN KEY (course_id)
        REFERENCES courses(course_id)
);

-- TABLE GRADES
CREATE TABLE grades (
    grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id NUMBER NOT NULL,
    score NUMBER(5,2),
    grade_letter VARCHAR2(2),
    CONSTRAINT fk_enrollment FOREIGN KEY (enrollment_id)
        REFERENCES enrollments(enrollment_id)
);

-- INDEX
CREATE INDEX idx_student_email ON students(email);

-- VIEW
CREATE OR REPLACE VIEW student_performance AS
SELECT 
    s.student_id,
    s.first_name,
    s.last_name,
    c.course_name,
    g.score,
    g.grade_letter
FROM students s
JOIN enrollments e ON s.student_id = e.student_id
JOIN courses c ON e.course_id = c.course_id
JOIN grades g ON e.enrollment_id = g.enrollment_id;

-- TRIGGER
CREATE OR REPLACE TRIGGER trg_grade_letter
BEFORE INSERT ON grades
FOR EACH ROW
BEGIN
    IF :NEW.score >= 16 THEN
        :NEW.grade_letter := 'A';
    ELSIF :NEW.score >= 14 THEN
        :NEW.grade_letter := 'B';
    ELSIF :NEW.score >= 12 THEN
        :NEW.grade_letter := 'C';
    ELSE
        :NEW.grade_letter := 'D';
    END IF;
END;
/